//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMolecules.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMolecules.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should have an id..
        /// </summary>
        internal static string AggregateRootShouldHaveIdDescription {
            get {
                return ResourceManager.GetString("AggregateRootShouldHaveIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should have an id.
        /// </summary>
        internal static string AggregateRootShouldHaveIdFormat {
            get {
                return ResourceManager.GetString("AggregateRootShouldHaveIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should have an id.
        /// </summary>
        internal static string AggregateRootShouldHaveIdTitle {
            get {
                return ResourceManager.GetString("AggregateRootShouldHaveIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should not reference repositories..
        /// </summary>
        internal static string AggregateRootShouldNotUseRepositoryDescription {
            get {
                return ResourceManager.GetString("AggregateRootShouldNotUseRepositoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should not reference repositories.
        /// </summary>
        internal static string AggregateRootShouldNotUseRepositoryFormat {
            get {
                return ResourceManager.GetString("AggregateRootShouldNotUseRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should not reference repositories.
        /// </summary>
        internal static string AggregateRootShouldNotUseRepositoryTitle {
            get {
                return ResourceManager.GetString("AggregateRootShouldNotUseRepositoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should not reference services..
        /// </summary>
        internal static string AggregateRootShouldNotUseServiceDescription {
            get {
                return ResourceManager.GetString("AggregateRootShouldNotUseServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should not reference services.
        /// </summary>
        internal static string AggregateRootShouldNotUseServiceFormat {
            get {
                return ResourceManager.GetString("AggregateRootShouldNotUseServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateRoots should not reference services.
        /// </summary>
        internal static string AggregateRootShouldNotUseServiceTitle {
            get {
                return ResourceManager.GetString("AggregateRootShouldNotUseServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should have an id..
        /// </summary>
        internal static string EntityShouldHaveIdDescription {
            get {
                return ResourceManager.GetString("EntityShouldHaveIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should have an id.
        /// </summary>
        internal static string EntityShouldHaveIdFormat {
            get {
                return ResourceManager.GetString("EntityShouldHaveIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should have an id.
        /// </summary>
        internal static string EntityShouldHaveIdTitle {
            get {
                return ResourceManager.GetString("EntityShouldHaveIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference aggregate roots..
        /// </summary>
        internal static string EntityShouldNotUseAggregateRootDescription {
            get {
                return ResourceManager.GetString("EntityShouldNotUseAggregateRootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference aggregate roots.
        /// </summary>
        internal static string EntityShouldNotUseAggregateRootFormat {
            get {
                return ResourceManager.GetString("EntityShouldNotUseAggregateRootFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference aggregate roots.
        /// </summary>
        internal static string EntityShouldNotUseAggregateRootTitle {
            get {
                return ResourceManager.GetString("EntityShouldNotUseAggregateRootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference repositories..
        /// </summary>
        internal static string EntityShouldNotUseRepositoryDescription {
            get {
                return ResourceManager.GetString("EntityShouldNotUseRepositoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference repositories.
        /// </summary>
        internal static string EntityShouldNotUseRepositoryFormat {
            get {
                return ResourceManager.GetString("EntityShouldNotUseRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference repositories.
        /// </summary>
        internal static string EntityShouldNotUseRepositoryTitle {
            get {
                return ResourceManager.GetString("EntityShouldNotUseRepositoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference services..
        /// </summary>
        internal static string EntityShouldNotUseServiceDescription {
            get {
                return ResourceManager.GetString("EntityShouldNotUseServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference services.
        /// </summary>
        internal static string EntityShouldNotUseServiceFormat {
            get {
                return ResourceManager.GetString("EntityShouldNotUseServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities should not reference services.
        /// </summary>
        internal static string EntityShouldNotUseServiceTitle {
            get {
                return ResourceManager.GetString("EntityShouldNotUseServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories should have an id..
        /// </summary>
        internal static string RepositoryShouldNotUseServiceDescription {
            get {
                return ResourceManager.GetString("RepositoryShouldNotUseServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories should not reference services.
        /// </summary>
        internal static string RepositoryShouldNotUseServiceFormat {
            get {
                return ResourceManager.GetString("RepositoryShouldNotUseServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories should not reference services.
        /// </summary>
        internal static string RepositoryShouldNotUseServiceTitle {
            get {
                return ResourceManager.GetString("RepositoryShouldNotUseServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should implement IEquatable&lt;ValueObject&gt;..
        /// </summary>
        internal static string ValueObjectMustImplementIEquatableDescription {
            get {
                return ResourceManager.GetString("ValueObjectMustImplementIEquatableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should implement IEquatable&lt;ValueObject&gt;.
        /// </summary>
        internal static string ValueObjectMustImplementIEquatableMessageFormat {
            get {
                return ResourceManager.GetString("ValueObjectMustImplementIEquatableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should implement IEquatable&lt;ValueObject&gt;.
        /// </summary>
        internal static string ValueObjectMustImplementIEquatableTitle {
            get {
                return ResourceManager.GetString("ValueObjectMustImplementIEquatableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should be immutable..
        /// </summary>
        internal static string ValueObjectShouldBeImmutableDescription {
            get {
                return ResourceManager.GetString("ValueObjectShouldBeImmutableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObjects should be immutable.
        /// </summary>
        internal static string ValueObjectShouldBeImmutableMessageFormat {
            get {
                return ResourceManager.GetString("ValueObjectShouldBeImmutableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObjects should be immutable.
        /// </summary>
        internal static string ValueObjectShouldBeImmutableTitle {
            get {
                return ResourceManager.GetString("ValueObjectShouldBeImmutableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should be declared as sealed..
        /// </summary>
        internal static string ValueObjectShouldBeSealedDescription {
            get {
                return ResourceManager.GetString("ValueObjectShouldBeSealedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should be declared as sealed.
        /// </summary>
        internal static string ValueObjectShouldBeSealedMessageFormat {
            get {
                return ResourceManager.GetString("ValueObjectShouldBeSealedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should be declared as sealed.
        /// </summary>
        internal static string ValueObjectShouldBeSealedTitle {
            get {
                return ResourceManager.GetString("ValueObjectShouldBeSealedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should not reference aggregate roots..
        /// </summary>
        internal static string ValueObjectUsesAggregateRootDescription {
            get {
                return ResourceManager.GetString("ValueObjectUsesAggregateRootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObjects should not use aggregate roots.
        /// </summary>
        internal static string ValueObjectUsesAggregateRootMessageFormat {
            get {
                return ResourceManager.GetString("ValueObjectUsesAggregateRootMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObject uses aggregate roots.
        /// </summary>
        internal static string ValueObjectUsesAggregateRootTitle {
            get {
                return ResourceManager.GetString("ValueObjectUsesAggregateRootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should not reference entities..
        /// </summary>
        internal static string ValueObjectUsesEntityDescription {
            get {
                return ResourceManager.GetString("ValueObjectUsesEntityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObjects should not use entities.
        /// </summary>
        internal static string ValueObjectUsesEntityMessageFormat {
            get {
                return ResourceManager.GetString("ValueObjectUsesEntityMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObject uses entities.
        /// </summary>
        internal static string ValueObjectUsesEntityTitle {
            get {
                return ResourceManager.GetString("ValueObjectUsesEntityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should not reference repositories..
        /// </summary>
        internal static string ValueObjectUsesRepositoryDescription {
            get {
                return ResourceManager.GetString("ValueObjectUsesRepositoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObjects should not use repositories.
        /// </summary>
        internal static string ValueObjectUsesRepositoryMessageFormat {
            get {
                return ResourceManager.GetString("ValueObjectUsesRepositoryMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObject uses repositories.
        /// </summary>
        internal static string ValueObjectUsesRepositoryTitle {
            get {
                return ResourceManager.GetString("ValueObjectUsesRepositoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value objects should not reference services..
        /// </summary>
        internal static string ValueObjectUsesServiceDescription {
            get {
                return ResourceManager.GetString("ValueObjectUsesServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObjects should not use services.
        /// </summary>
        internal static string ValueObjectUsesServiceMessageFormat {
            get {
                return ResourceManager.GetString("ValueObjectUsesServiceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueObject uses services.
        /// </summary>
        internal static string ValueObjectUsesServiceTitle {
            get {
                return ResourceManager.GetString("ValueObjectUsesServiceTitle", resourceCulture);
            }
        }
    }
}
